// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_dMN4uR3nCygSckuKhBaDqCaCeGl6gVg',
    appId: '1:12725935403:web:a712ce2a7f19e51b8a396e',
    messagingSenderId: '12725935403',
    projectId: 'university-bus-system-c14e9',
    authDomain: 'university-bus-system-c14e9.firebaseapp.com',
    storageBucket: 'university-bus-system-c14e9.firebasestorage.app',
    measurementId: 'G-V3FX2243KL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-DKdzHqWH8I3ClbKYY_T4NwGGLW30TMY',
    appId: '1:12725935403:android:0a581e9331fcaff58a396e',
    messagingSenderId: '12725935403',
    projectId: 'university-bus-system-c14e9',
    storageBucket: 'university-bus-system-c14e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUWTlBYMjApWPSDQtGsrxnmI_EkkIZJRo',
    appId: '1:12725935403:ios:4b97fd2180e664c88a396e',
    messagingSenderId: '12725935403',
    projectId: 'university-bus-system-c14e9',
    storageBucket: 'university-bus-system-c14e9.firebasestorage.app',
    iosBundleId: 'com.example.movesUni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUWTlBYMjApWPSDQtGsrxnmI_EkkIZJRo',
    appId: '1:12725935403:ios:4b97fd2180e664c88a396e',
    messagingSenderId: '12725935403',
    projectId: 'university-bus-system-c14e9',
    storageBucket: 'university-bus-system-c14e9.firebasestorage.app',
    iosBundleId: 'com.example.movesUni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_dMN4uR3nCygSckuKhBaDqCaCeGl6gVg',
    appId: '1:12725935403:web:2d3a2993be80c8188a396e',
    messagingSenderId: '12725935403',
    projectId: 'university-bus-system-c14e9',
    authDomain: 'university-bus-system-c14e9.firebaseapp.com',
    storageBucket: 'university-bus-system-c14e9.firebasestorage.app',
    measurementId: 'G-GPRE1QJS58',
  );
}
